version: "2.4"
services:

  mysql:
    image: mysql/mysql-server
    container_name: mysqldb
    networks:
      - ppmtool
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=task
      - MYSQL_USER=prateek
      - MYSQL_PASSWORD=Prateek@123
    volumes:
      - mysql_data_volume:/var/lib/mysql
    ports:
      - "9001:3306"
  react:
    image: prateek1o1/mytaskguru-frontend:latest
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - ppmtool
    depends_on:
      - spring
    command: npm start
  spring:
    image: prateek1o1/mytaskguru-backend:latest
    container_name: server
    ports:
      - "3002:3002"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/task?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    networks:
      - ppmtool
    depends_on:
      mysql:
        condition: service_healthy
    command: java -jar MyTaskGuru-0.0.1-SNAPSHOT.jar


networks:
  ppmtool:

volumes:
  mysql_data_volume: