version: "2.4"
services:

  mysql:
    image: mysql/mysql-server
    container_name: mysql
    networks:
      - my-net
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=project
      - MYSQL_USER=prateek
      - MYSQL_PASSWORD=Prateek@123
    volumes:
      - mysql_data_volume:/var/lib/mysql

  react:
    image: prateek1o1/mytaskguru-frontend
    container_name: mytaskguru-frontend
    ports:
      - "3000:3000"
    networks:
      - my-net
    depends_on:
      - spring

  spring:
    image: prateek1o1/mytaskguru-backend
    container_name: mytaskguru-frontend
    ports:
      - "3002:3002"
    networks:
      - my-net
    depends_on:
      mysql:
        condition: service_healthy


networks:
  my-net:

volumes:
  mysql_data_volume:
