version: "3.8"
services:

  mysqldb:
    image: mysql
    container_name: mysqldb
    ports:
      - "3307:3306"
    restart: always
    networks: 
      springboot-mysql-net: 
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=task
      - MYSQL_USER=prateek
      - MYSQL_PASSWORD=prateek@123
    volumes:
      - mysql_data_volume:/var/lib/mysql
  react:
    image: prateek1o1/mytaskguru-frontend:latest
    container_name: client
    ports:
      - "3000:3000"
    networks:
      springboot-mysql-net
    depends_on:
      - springboot-restful-webservices
  springboot-restful-webservices:
    image: prateek1o1/mytaskguru-backend:latest
    container_name: springboot-restful-webservices
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    restart: always
    environment:
      spring_datasource_url: "jdbc:mysql://mysqldb:3306/task?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
      spring_datasource_username: prateek
      spring_datasource_password: prateek@123
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net
    restart: on-failure
  


networks:
  springboot-mysql-net:

volumes:
  mysql_data_volume: