---
version: "2.4"
services:
  mytaskguru-frontend:
    image: prateek1o1/mytaskguru-frontend:latest
    container_name: mytaskguru-frontend
    ports:
      - 3000:3000
    command: npm start
    networks:
      - mytaskguru-network
    depends_on:
      - mytaskguru-backend
    volumes:
      - mysql_data_volume:/var/lib/mysql
  mytaskguru-backend:
    image: prateek1o1/mytaskguru-backend:latest
    container_name: mytaskguru-backend
    ports:
      - 3002:3002
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ppm?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mytaskguru-network
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=project
      - MYSQL_USER=prateek
      - MYSQL_PASSWORD=Prateek@123
    ports:
      - 3307:3306
    networks:
      - mytaskguru-network
networks:
  mytaskguru-network: null
volumes:
  mysql_data_volume: null
