version: "3.8"
services:

  mysqldb:
    image: mysql
    container_name: mysqldb
    networks: 
      springboot-mysql-net: 
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=task
    volumes:
      - mysql_data_volume:/var/lib/mysql
  # react:
  #   image: prateek1o1/mytaskguru-frontend:latest
  #   container_name: client
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     springboot-mysql-net: 
  #       ipv4_address: 172.30.0.4
  #   depends_on:
  #     - spring
  springboot-restful-webservices:
    image: prateek1o1/mytaskguru-backend:latest
    container_name: springboot-restful-webservices
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/database?autoReconnect=true&useSSL=false
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net
    restart: on-failure
  


networks:
  springboot-mysql-net:

volumes:
  mysql_data_volume: